### ISSUE TITLE
Add __str__() for organizations

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#16]
![screenshot from 2015-06-27 17 23 24](https://cloud.githubusercontent.com/assets/801549/8393915/4352744c-1cf1-11e5-9388-c6e3d3545a7b.png)

**Comment by EricHorton** [comment]
Implement __unicode__() instead to be compliant with current standards.

**Comment by srmagura** [comment]
That's a Python 2 thing. Python 2 __unicode__ is essentially equivalent to Python 3 __str__
http://stackoverflow.com/a/1307210/752601
