### ISSUE TITLE
Is there a possibility of session UUID collisions?

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#17]
Currently, I believe the admin user would receive a cryptic error in the case of a collision. The code should handle the collision without involving the user. I propose modifying `Session.save()` to handle the exception if it occurs.

**Comment by EricHorton** [comment]
The pyhon uuid package provides several implementations of uuid standards. The one currently implemented, uuid1, is guaranteed to be unique so long as no two are created at the same instant.

http://stackoverflow.com/questions/703035/when-are-you-truly-forced-to-use-uuid-as-part-of-the-design/786541#786541

**Comment by srmagura** [comment]
I didn't know about that. That's cool.
