### ISSUE TITLE
Trying to view DefaultAdmin causes error

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#19]
To reproduce:
1. Log in to admin site
2. Go to auth > users
3. Click on DefaultAdmin

Django should return an error page. The error is internal to Django, i.e. not our code. Likely conclusion is that something about the DefaultAdmin record in the database is not as Django expects it to be.

**Comment by EricHorton** [comment]
Fixed. 3e7d6b868a1cf9370c4f9b02d99c52043d4a247b
