### ISSUE TITLE
Registration form fields are incorrect

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#23]
See pic. The organization dropdown should be gone. There should be an organization code field instead. Possibly a version control mistake?

![screenshot from 2015-06-28 22 14 23](https://cloud.githubusercontent.com/assets/801549/8399840/8663d65c-1de3-11e5-893d-21911cc94ae0.png)

**Comment by EricHorton** [comment]
What version are you on, and are you hosting it locally? 

The registration form should be different. 

Eric Horton

**Comment by srmagura** [comment]
I got sent to goodnight-lead.herokuapp.com without me realizing it, due to #24. Closing this issue.
