### ISSUE TITLE
Registration: change "major" to "Major / career field"

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#26]
It's currently a text field. Make it a dropdown. 

This is the list of fields that Laura suggested:
business; education; engineering; design & fine arts; humanities; law; life sciences; math & physical sciences; medicine; social sciences; health; applied fields

**Comment by EricHorton** [comment]
Implemented: f2dcbc16a266753b5e15b4cb7a0b3e54da96c6e5.
