### ISSUE TITLE
Account settings: date formatting

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#34]
1. Format used by date picker: 07/21/2015
2. Format used by Django, when generating the form on the Account settings page: 2015-07-21

Task: change (2) so that it matches (1), in terms of what the user sees

**Comment by EricHorton** [comment]
Fixed 47a51d04138caccc7ca678c1c56682d9e0858db3.

**Comment by srmagura** [comment]
(Unless there is some reason why this is infeasible to do) I would like to display the date as mm/dd/yyyy, as I said when I posted this issue. Sorry if it was unclear.

Reasons for this design decision:
1. yyyy-mm-dd is not a date format people are used to seeing, so it may be confusing
2. Registration form uses mm/dd/yyyy and I want date formatting to be consistent across the site.

**Comment by srmagura** [comment]
Actually nvm about reason 2

**Comment by srmagura** [comment]
Actually i don't care

**Comment by srmagura** [comment]
I might change it myself eventually but it's not important enough to warrant an open issue
