### ISSUE TITLE
Extra space added on "Change sample"

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#38]
Everytime you submit the change sample form, extra space gets added to the panel at the bottom that has the mean, stdev, .etc

![image](https://cloud.githubusercontent.com/assets/801549/9053912/632de7e0-3a49-11e5-833a-dd566bbe0a1d.png)

**Comment by EricHorton** [comment]
1b8fb16f930eb861fb641e775303c2fa8b78b87f
