### ISSUE TITLE
Improvements to VIA plot

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#40]
1. Bars are not directly above their corresponding labels --- need to fix this
2. The label on the vertical axis ("Value") doesn't tell the user anything... Change it to something more descriptive like "# of users of who have this strength as a signature strength". 
![image](https://cloud.githubusercontent.com/assets/801549/9144246/ae195fd2-3d19-11e5-9dd1-cb804731f53a.png)

3. The popup box that appears when you hover over a bar shows the **category** name but it would be more clear if it showed the **strength** name. In the example below, I would like the box to say "Perspective" rather than "Wisdom and Knowledge".
![image](https://cloud.githubusercontent.com/assets/801549/9144347/46a3ec2c-3d1a-11e5-9c88-cfab87c28527.png)

**Comment by EricHorton** [comment]
https://github.com/alexandersimoes/d3plus/issues/355

**Comment by EricHorton** [comment]
622f06ac7b507b637b188774ceced6c1171797ca

**Comment by srmagura** [comment]
Nice, much better
