### ISSUE TITLE
Saving plots to images

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#44]
In the statistics requirements document, a requirement states that there must be a way to save the plots as images. This is useful because admins may want to email plots, put them in slideshows, .etc.

Of course you can get an image of one of our plots by taking a screenshot... but is there a better way? If there is no better way, this is not a big problem --- it can be set as a goal for a future iteration.

**Comment by EricHorton** [comment]
Images are rendered as svg by javascript. The way to download an image would be to encode the svg into base64 and route it through the server to convert into an image and download. Javascript itself cannot create files as a security measure.

I've been looking into it.

**Comment by srmagura** [comment]
that's about what I thought. we'll leave this as a feature for a future iteration

**Comment by srmagura** [comment]
closing this so it disappears from my "Issues" page LOL
