### ISSUE TITLE
"No data available" when sample size = 1

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#45]
To reproduce:
1. Make sure you have the latest commit
2. python3 manage.py insert_test_data
3. Go to statistics page and change sample to organization=Incompletionists.
4. Try to view the plot for Ambiguity --- it says the sample size is 1 but the plot area says "No Data Available". 

If we can't show anything in a boxplot when sample size is 1, that inventory should not be included in the dropdown (the dropdown that changes which plot is shown).

![image](https://cloud.githubusercontent.com/assets/801549/9262615/4c0f5cea-41e4-11e5-87aa-1e3dcc0db734.png)

**Comment by srmagura** [comment]
This issue doesn't affect the VIA plot

**Comment by srmagura** [comment]
Relevant wiki page -- documentation of insert_test_data: https://github.com/srmagura/goodnight-lead/wiki/Management-commands

**Comment by EricHorton** [comment]
53da647bdb4832a4c343b34af6dac246d4a5a400
