### ISSUE TITLE
Session names must be unique

### ISSUE THREAD

**Issue by srmagura** [srmagura/goodnight-lead#46]
Our Session model requires their names to be unique. I think it would be better if this uniqueness was enforced only for sessions inside the same organization.

E.g.
* Both Organization1 and Organization2 should be able to have sessions named "Fall 2016". (doing this is currently rejected by our model validation)
* But Organization1 is not allowed to have more than one session named "Fall 2016". (this is how things are now, and that's how it should be)

**Comment by EricHorton** [comment]
3799630212cf426639b59af0b05007286cdc5167

This one requires a database migration.
